Gossip-app/config/routes.rb
Rails.application.routes.draw do

  get 'likes/index'
  get 'likes/show'
  get 'likes/new'
  get 'likes/create'
  get 'likes/destroy'
  
  root 'home#show'

  get 'home', to: 'home#show'
  get 'welcome/:user_first_name', to: 'welcome#show'
  get 'team', to: 'team#show'
  get 'contact', to: 'contact#show'

  resources :sessions, only: [:new, :create, :destroy]
  resources :users, only: [:new, :create, :show]
  resources :gossips do 
    resources :comments, except: [:index, :show]
    resources :likes, only: [:new, :create, :destroy]
  end
  resources :cities
  resources :profile, only: [:show, :edit, :update, :destroy]
  
end

Gossip-app/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

Gossip-app/app/models/city.rb
class City < ApplicationRecord
  has_many :users

  validates :name, presence: true

  
end

Gossip-app/app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :gossip
  belongs_to :user

  validates :content, presence: true
end

Gossip-app/app/models/gossip.rb
class Gossip < ApplicationRecord
  belongs_to :user
  has_many :gossip_tag_joins
  has_many :tags, through: :gossip_tag_joins
  has_many :comments
  has_many :likes

  validates :title, presence: true, length: { in: 3..20 }
  validates :content, presence: true
  validates :user_id, presence: true 
end

Gossip-app/app/models/join_gossip_tag.rb
class JoinGossipTag < ApplicationRecord
  belongs_to :gossip
  belongs_to :tag
end

Gossip-app/app/models/like.rb
class Like < ApplicationRecord
  belongs_to :gossip
end

Gossip-app/app/models/private_message.rb
class PrivateMessage < ApplicationRecord
  belongs_to :sender, class_name: "User" #indique que PrivateMessage appartient à un sender, qui est en fait de la classe User
  belongs_to :recipient, class_name: "User" #indique que PrivateMessage appartient à un recipient, qui est en fait de la classe User
end

Gossip-app/app/models/tag.rb
class Tag < ApplicationRecord
  has_many :gossip_tag_joins
  has_many :gossips, through: :gossip_tag_joins
end

Gossip-app/app/models/user.rb
class User < ApplicationRecord
  belongs_to :city
  has_many :gossips
  has_many :comments
  has_many :likes
  has_many :sent_messages, foreign_key: 'sender_id', class_name: "PrivateMessage" 
  has_many :received_messages, foreign_key: 'recipient_id', class_name: "PrivateMessage" 
  
  has_secure_password 
  
  validates :password, presence: true, length: { minimum: 6 }
  validates :first_name, presence: true
  validates :last_name, presence: true
  validates :email,
    presence: true,
    uniqueness: true,
    format: { with: /\A[^@\s]+@([^@\s]+\.)+[^@\s]+\z/, message: "Please enter a valid email adress" } 


  def remember(remember_token)
    remember_digest = BCrypt::Password.create(remember_token)
    self.update(remember_digest: remember_digest)
  end
end

Gossip-app/app/helpers/cities_helper.rb
module CitiesHelper
end

Gossip-app/app/helpers/comments_helper.rb
module CommentsHelper

  def is_permitted_comment?
    @gossip = Gossip.find(params[:gossip_id])
    @comment = Comment.find(params[:id])
    @user = User.find(@comment.user_id)
    unless current_user == @user
      flash[:danger] = "Vous n'êtes pas autorisé(e) à modifier ou supprimer ce commentaire"
      redirect_to gossip_path(@gossip.id)
    end
  end

end

Gossip-app/app/helpers/contact_helper.rb
module ContactHelper
end

Gossip-app/app/helpers/gossips_helper.rb
module GossipsHelper
  
  def is_permitted_gossip?
    @gossip = Gossip.find(params[:id])
    @user = User.find(@gossip.user_id)
    unless current_user == @user
      flash[:danger] = "Vous n'êtes pas autorisé(e) à modifier ou supprimer ce gossip"
      redirect_to gossip_path(@gossip.id)
    end
  end

end

Gossip-app/app/helpers/home_helper.rb
module HomeHelper
end

Gossip-app/app/helpers/likes_helper.rb
module LikesHelper
end

Gossip-app/app/helpers/profile_helper.rb
module ProfileHelper
end

Gossip-app/app/helpers/sessions_helper.rb
module SessionsHelper
  
  # identifier plus rapidement l'utilisateur grâce aux sessions >>> à appeler à la page login mais aussi juste après la création d'un nouvel utilisateur (par exemple).
  def log_in(user) 
    session[:user_id] = user.id
  end

  # créer le cookie avec un token qui sera stocké dans le navigateur du user, et stocker de manière sécurisée dans le remember_digest en base de données
  def remember(user)
    # ici je vais créer un remember_token qui est une suite aléatoire de caractères
    remember_token = SecureRandom.urlsafe_base64
    # j'ai mon token, je vais stocker son digest en base de données via la méthode remember du model user :    
    user.remember(remember_token)
    #  maintenant, je vais créer les cookies : un cookie qui va conserver l'user_id, et un autre qui va enregistrer le remember_token
    cookies.permanent[:user_id] = user.id
    cookies.permanent[:remember_token] = remember_token
  end

  def current_user
    if session[:user_id] # vérifier s'il y a bien une session contenant l'id de notre utilisateur
      current_user = User.find_by(id: session[:user_id]) # trouver l'instance de User contenant les infos de ton utilisateur connecté
    elsif cookies[:user_id] # vérifier s'il y a bien un cookie contenant l'id de notre utilisateur
      user = User.find_by(id: cookies[:user_id]) # trouver l'utilisateur en DB à partir du cookie qui stocke le user_id
      if user && BCrypt::Password.new(user.remember_digest).is_password?(cookies[:remember_token]) # prendre le remember_token stocké en cookie, le hasher, puis le comparer avec notre remember_digest stocké en base
        log_in user # si tout est bon, il ne nous reste plus qu'à souhaiter bienvenue à l'utilisateur !
        current_user = user # et reconnaitre que le user trouvé avec la session est le même que celui trouvé avec le cookie 
      end
    end
  end

  # vérifier que l'utilisateur est bien connecté (par exemple pour ensuite lui donner accès à certaines views)
  def logged_in? #https://levelup.gitconnected.com/simple-authentication-guide-with-ruby-on-rails-16a6255f0be8  
    !current_user.nil? # autre solution >>> session[:user_id] ou session.key?(:user_id)
  end

  # vérifier que l'utilisateur est bien connecté (par exemple pour ensuite lui donner accès à certaines views)
  def authenticate_user
    unless current_user
      flash[:danger] = "Please log in."
      redirect_to new_session_path
    end
  end

  # effacer les cookies et remettre le remember_digest à nil.
  def forget(user)
    # on remet le remember_digest à nil puisqu'il ne nous servira plus :
    user.update(remember_digest: nil)
    # on efface les cookies dans le navigateur de l'utilisateur
    cookies.delete(:user_id)
    cookies.delete(:remember_token)
  end

  # méthode log_out(user) complète tenant compte de la destruction des cookies >>> à appeler dans la méthode destroy du sessions_controller
  def log_out(user)
    session.delete(:user_id)
    forget(user)
  end

end

Gossip-app/app/helpers/team_helper.rb
module TeamHelper
end

Gossip-app/app/helpers/users_helper.rb
module UsersHelper
end

Gossip-app/app/helpers/welcome_helper.rb
module WelcomeHelper
end

Gossip-app/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    
    <title>GossipApp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-F3w7mX95PdgyTmZZMECAngseQB83DfGTowi0iMjiWaeVhAn4FJkqJByhZMI3AhiU" crossorigin="anonymous" />
  
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <header>
    
    <nav class="navbar navbar-expand-lg navbar-dark bg-primary fixed-top py-3" id="mainNav">
      
      <div class="container px-4 px-lg-5">
        <a class="navbar-brand" href="<%= root_path %>">Gossip</a>
        <button class="navbar-toggler navbar-toggler-right" type="button" data-bs-toggle="collapse" data-bs-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation"><span class="navbar-toggler-icon"></span></button>
        
        <div class="collapse navbar-collapse" id="navbarResponsive">
          <ul class="navbar-nav ms-auto my-1 my-lg-0">
            
            <% if logged_in? %>
              <li class="nav-item"><a class="nav-link" href="<%= team_path %>">Team</a></li>
              <li class="nav-item"><a class="nav-link" href="<%= contact_path %>">Nous contacter</a></li>
              <li class="nav-item"><%= link_to "Se déconnecter", session_path(session.id), method: :delete, class: "nav-link btn btn-outline-danger text-light" %></li>
              
              <% else %>
              <li class="nav-item"><a class="nav-link" href="<%= team_path %>">Team</a></li>
              <li class="nav-item"><a class="nav-link" href="<%= contact_path %>">Nous contacter</a></li>
              <li class="nav-item">
                <div class="dropdown">
                  <button class="btn btn-secondary dropdown-toggle" type="button" id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">Connexion</button>
                  <div class="dropdown-menu" aria-labelledby="dropdownMenuButton">
                    <a class="dropdown-item" href="<%= new_session_path %>">Se connecter</a>
                    <a class="dropdown-item" href="<%= new_user_path %>">S'inscrire</a>
                  </div>
                </div>
              </li>
            <% end %>
          </ul>
        </div>
      </div>
    </nav>
  </header>

  <body>
    <%= yield %>


    <footer class="bg-light py-3 ">
      <div class="container col-md-12">
        <div class="small text-center align-center justify-center text-muted">Copyright &copy; 2022, COURAGE</div>
      </div>
    </footer>

    <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>

  </body>
</html>