Gossip-app/config/routes.rb
Rails.application.routes.draw do

  get 'likes/index'
  get 'likes/show'
  get 'likes/new'
  get 'likes/create'
  get 'likes/destroy'
  
  root 'home#show'

  get 'home', to: 'home#show'
  get 'welcome/:user_first_name', to: 'welcome#show'
  get 'team', to: 'team#show'
  get 'contact', to: 'contact#show'

  resources :sessions, only: [:new, :create, :destroy]
  resources :users, only: [:new, :create, :show]
  resources :gossips do 
    resources :comments, except: [:index, :show]
    resources :likes, only: [:new, :create, :destroy]
  end
  resources :cities
  resources :profile, only: [:show, :edit, :update, :destroy]
  
end

Gossip-app/app/models/gossip.rb
class Gossip < ApplicationRecord
  belongs_to :user
  has_many :gossip_tag_joins
  has_many :tags, through: :gossip_tag_joins
  has_many :comments
  has_many :likes

  validates :title, presence: true, length: { in: 3..20 }
  validates :content, presence: true
  validates :user_id, presence: true 
end

Gossip-app/app/controllers/gossips_controller.rb
class GossipsController < ApplicationController
  before_action :authenticate_user
  before_action :is_permitted_gossip?, only: [:edit, :update, :destroy]

  def index # Méthode qui récupère tous les potins et les envoie à la view index (index.html.erb) pour affichage
    puts "#" * 60
    puts "Home controller required to GET index.html.erb from home view"
    puts "#" * 60

    @gossips = Gossip.all #transmettre les données de la table gossips à la view (sous forme d'array de hashs)
  end

  def show # Méthode qui récupère le potin concerné et l'envoie à la view show (show.html.erb) pour affichage
    puts "#" * 60
    puts "Gossip controller required to GET show.html.erb from gossip view, with dynamic URL variable"
    puts  params[:id] #idem que params["gossip_id"] >>> récupérer la valeur contenue dans l'URL - à l'endroit où on a initialisé la variable dans un GET (i.e fichier routes/rb >>> gossip/:gossip_id) - stockée dans un hash temporaire "params" {"gossip_id"=>"valeur_dans_URL"} 
    puts "#" * 60

    @gossip = Gossip.find(params[:id]) #pour cibler le gossip concerné dans la base de donnée 
  end

  def new # Méthode qui crée un potin vide et l'envoie à une view qui affiche le formulaire pour 'le remplir' (new.html.erb)
    @gossip = Gossip.new #pour éviter une method error sur les alerts https://stackoverflow.com/questions/40192004/ruby-on-rails-undefined-method-errors-for-nilnilclass
  end

  def create
    # Méthode qui créé un potin à partir du contenu du formulaire de new.html.erb, soumis par l'utilisateur
    # pour info, le contenu de ce formulaire sera accessible dans le hash params (ton meilleur pote)
    # Une fois la création faite, on redirige généralement vers la méthode show (pour afficher le potin créé)
    puts "#" * 60
    puts "Ceci est le contenu de params :"
    puts params
    puts "#" * 60

    @gossip = Gossip.new(gossip_params) # création d'un nouveau gossip avec les données obtenues à partir du formulaire,
    @gossip.user = current_user #affecter l'auteur du gossip au user connecté via le session helper 
    if @gossip.save # essaie de sauvegarder en base @gossip
      redirect_to gossips_path
      flash[:success] = "Le Gossip a bien été créé."  # si ça marche, il redirige vers la page d'index du site, en passant par la route sélectionnée, donc ton app repart sur un controller, sa méthode, etc.
    else
      render :new # sinon, il render directement la view new (qui est celle sur laquelle on est déjà) tout en gardant les variables disponibles (notamment @gossip)
      flash[:warning] = @gossip.errors.full_messages

      puts "#" * 60
      puts "Ceci est le contenu de params :"
      puts @gossip.errors.full_messages
      puts "#" * 60
    end
    # doc Ruby pour redirect_to et render : https://guides.rubyonrails.org/layouts_and_rendering.html#using-render
    # doc pour Flash messages : https://www.rubyguides.com/2019/11/rails-flash-messages/
  end

  def edit # Méthode qui récupère le potin concerné et l'envoie à la view edit (edit.html.erb) pour affichage dans un formulaire d'édition
    @gossip = Gossip.find(params[:id])
  end

  # Focus sur form_for (à coder dans views)
  # Pour générer un formulaire qui correspond à un model en particulier, il y a une méthode qui s'appelle form_for. 
  # Cette méthode prend en paramètre l'enregistrement que vous souhaitez modifier (ici @gossip) et un block qui aura comme paramètre un FormBuilder, qui est un objet qui va nous permettre de générer les différents champs.

  def update 
    # Méthode qui met à jour le potin à partir du contenu du formulaire de edit.html.erb, soumis par l'utilisateur
    # pour info, le contenu de ce formulaire sera accessible dans le hash params
    # Une fois la modification faite, on redirige généralement vers la méthode show (pour afficher le potin modifié)
    @gossip = Gossip.find(params[:id])
    
    if @gossip.update(gossip_params)
      redirect_to gossip_path(@gossip.id)
      flash.now[:success] = "Le Gossip a bien été modifié."
    else
      flash.now[:warning] = @gossip.errors.full_messages
      render 'edit'
    end
  end

  def destroy 
    # Méthode qui récupère le potin concerné et le détruit en base
    # Une fois la suppression faite, on redirige généralement vers la méthode index (pour afficher la liste à jour)
    @gossip = Gossip.find(params[:id])
    @gossip.destroy
    redirect_to gossips_path
    flash[:success] = "Le Gossip a bien été supprimé."
  end

  private 
  
  def gossip_params
    params.require(:gossip).permit(:title, :content)
  end

end

Gossip-app/app/helpers/gossips_helper.rb
module GossipsHelper
  
  def is_permitted_gossip?
    @gossip = Gossip.find(params[:id])
    @user = User.find(@gossip.user_id)
    unless current_user == @user
      flash[:danger] = "Vous n'êtes pas autorisé(e) à modifier ou supprimer ce gossip"
      redirect_to gossip_path(@gossip.id)
    end
  end

end

Gossip-app/app/views/gossips/edit.html.erb
<body class="text-center">
  <br/><br/><br/>
  <!-- Alerts / Flash messages -->
  <% flash.each do |key, msg| %>
    <div class="alert alert-<%=key%> text-center" role="alert">
      <%= msg %>
    </div>
  <% end %>

  <br/><br/>
  <h1>Modifier un gossip</h1>
  <br/><br/>

  <%= form_for @gossip do |f| %>
    <div class="form-group">
      <label>Titre du gossip</label>
      <%= f.text_field :title, class: 'form-control' %>
      <br/>
    </div>
    <div class="form-group">    
      <label>Contenu du gossip</label>
      <%= f.text_area :content, class: 'form-control' %>
      <br/>
    </div>
    <div class="form-group">
      <button type="submit" class="btn btn-primary">Valider</button>
    </div>
  <% end %>

  <br/><br/><br/><br/>
</body>

Gossip-app/app/views/gossips/index.html.erb
<!-- Alerts / Flash messages -->
<br/><br/><br/>
<% flash.each do |key, msg| %>
  <div class="alert alert-<%=key%> text-center" role="alert">
    <%= msg %>
  </div>
<% end %>
<br/><br/><br/>
<h4> Le flot de ragots </h4>

<div class="container-fluid d-flex flex-wrap justify-content-center row xy-3 ">
<% @gossips.each_with_index do |gossip, index| %>
  <div class="card border-primary mb-3" style="width: 18rem;">
  <div class="card-body">
    <h5 class="card-title"><%=gossip.title%></h5>
    <h6 class="card-subtitle mb-2 text-muted"><%=gossip.user.first_name%></h6>
    <p class="card-text"><%=gossip.content%></p>
    <small>Nombre de commentaires : <%= gossip.comments.count %></small><br/>
    <small>Nombre de likes : <%=gossip.likes.count%></small><br/>
    <a class="btn btn-outline-primary btn-sm" role="button" href="<%= gossip_path(gossip.id) %>">Voir le détail</a>
  </div>
</div>
  
  <br/>
<% end %>
</div>
<br/><br/><br/><br/>

Gossip-app/app/views/gossips/new.html.erb
<body class="text-center">
  <br/><br/><br/>
  <!-- Alerts / Flash messages -->
  <% flash.each do |key, msg| %>
    <div class="alert alert-<%=key%> text-center" role="alert">
      <%= msg %>
    </div>
  <% end %>


  <br/><br/>
  <h1>Créer un Ragot</h1>
  <br/><br/>

  <%= form_for @gossip do |f| %>
    <div class="form-group">
      <label>Titre du gossip</label>
      <%= f.text_field :title, placeholder: 'Titre', class: 'form-control' %>
      <br/>
    </div>
    
    <div class="form-group">    
      <label>Contenu du gossip</label>
      <%= f.text_area :content, placeholder: 'Contenu', class: 'form-control' %>
      <br/>
    </div>
    
    <div class="form-group">
      <button type="submit" class="btn btn-primary">Valider</button>
    </div>
  <% end %>

  <br/><br/><br/><br/>
</body>

Gossip-app/app/views/gossips/show.html.erb
<body>
  <br/><br/><br/>
  <!-- Alerts / Flash messages -->
    <% flash.each do |key, msg| %>
      <div class="alert alert-<%=key%> text-center" role="alert">
        <%= msg %>
      </div>
    <% end %>

  <div class="container">
    <div class="card">
      <div class="card-header">
        <h3>Titre : <%=@gossip.title%></h3>
      </div>
      <div class="card-body">
        <h4 class="card-title">Contenu : <%=@gossip.content%></h4>
        <hr class="my-4 ">
        <p class="card-text">
          <ul>
            <li>Créé le : <%=@gossip.created_at%></li>
            <li>Gossip n°<%=@gossip.id%></li>
            <li>Auteur : <%=@gossip.user.first_name%> <%=@gossip.user.last_name%></li>
            <li>Nombre de likes : <%=@gossip.likes.count%><li>
            <a class="btn btn-outline-secondary btn-sm" role="button" href="<%=user_path(@gossip.user.id)%>">A propos de l'auteur</a>
            <li>Ville : <%=@gossip.user.city.name%></li>
            <a class="btn btn-outline-secondary btn-sm" role="button" href="<%=city_path(@gossip.user.city_id)%>">Voir les gossips de <%=@gossip.user.city.name%></a>
            <br/>
          </ul>
        </p>
      </div>
      <div class="card-footer justify-content-around">
        <a class="btn btn-outline-success btn-sm" <%= link_to "Like", gossip_likes_path(@gossip.id), method: :post %>></a>
        <a class="btn btn-warning btn-sm" role="button" href="<%=edit_gossip_path(@gossip.id)%>">Modifier le gossip</a>
        <a class="btn btn-danger btn-sm" <%= link_to "Supprimer le gossip", gossip_path(@gossip.id), method: :delete, data: { confirm: "Are you sure?" } %>></a>
      </div>
    </div>
  </div>
  
  <div class= "container pt-5 pb-2">
    <br/>
    <h3> Lache ton com' </h3>
    <div class="pb-1 pt-1">
    <%= form_tag(gossip_comments_path(@gossip.id), method: "post") do %>
      <%= text_field_tag 'gossip_id', @id, type: 'hidden', class: 'form-control' %>
      <div class="form-group">
        <%= text_area_tag 'content', '', class: 'form-control mt-3' %>
      </div>
      <%= submit_tag "Envoyer", class: 'btn btn-outline-primary btn-sm mt-3 ' %>
    <% end %>
  </div>

  <div class= "container pt-5 pb-2">
    <h3> Liste des commentaires </h3><br/>
    <div class="list-group mx-auto">
      <% @gossip.comments.reverse.each do |comment| %>
        <div class="list-group-item mb-2">
          <div class="row">
            <div class="col-9">
              <p class="mb-2 fs-5"><%= comment.content %></p>
              <p class="mb-2 text-muted">By <%= comment.user.first_name%></p>
              <br/>
              <a class="btn btn-warning btn-sm" role="button" href="<%=edit_gossip_comment_path(@gossip.id, comment.id)%>">Modifier le commentaire</a>
              <a class="btn btn-danger btn-sm" href="<%= gossip_comment_path(@gossip.id, comment.id) %>" data-confirm="Etes-vous sûr de vouloir supprimer ce commentaire ?" data-method="DELETE">Supprimer le commentaire</a>
            </div>
          </div>
        </div>
      <% end %>
    </div>
  </div>
  
  <br/><br/>
  <div class="container text-center">
    <a class="btn btn-primary btn-lg" role="button" href="<%=root_path%>">Revenir à l'accueil</a>
  </div>
  <br/><br/><br/><br/>
</body>